### ISSUE TITLE
Ampersand breaks email_add method

### ISSUE THREAD

**Issue by broseborough** [ePublishing/exact_target#4]
Any time I use email_add I get an error saying that A CDATA section was not closed. 
I tried to create the simplest possible example that reproduces the issue, and I have isolated the problem to the ampersand character (&) in the body. 
It looks like this in irb after i have configured the ExactTarget class:

`>> email_id = ExactTarget.email_add('Title', 'Subject', :body=>'<html><body>&nbsp;</body></html>')
ExactTarget::Error: ExactTarget error #39: XML Parse Error = Error!!! Error Code = -1072896668, 
Line Number = 1, Reason = A CDATA section was not closed.
, API Call:<?xml version="1.0"?><exacttarget><authorization><username>MyUsername</username>
<password>MyPassword</password></authorization><system><system_name>email</system_name>
<action>add</action><sub_action>HTMLPaste</sub_action><category/><email_name> Title </email_name>
<email_subject> Subject 
</email_subject><email_body><![CDATA[<html><body>
 from /Library/Ruby/Gems/1.8/gems/exact-target-0.0.5/lib/exact_target.rb:111:in`parse_response_xml'
 from /Library/Ruby/Gems/1.8/gems/exact-target-0.0.5/lib/exact_target.rb:67:in `call'
 from /Library/Ruby/Gems/1.8/gems/exact-target-0.0.5/lib/exact_target.rb:90:in`email_add'
 from (irb):6`

**Comment by broseborough** [comment]
In an email from David McCullars:

From looking into it a little bit tonight, however, it strikes me as a problem on ET's end (though I confess that seems less likely than a bug in the gem).  The response back from ET is that the CDATA section was not closed, and Nokogiri is successfully parsing the response xml and raising the ruby error with the error description.  So that tells me that either ET is having trouble, or our request xml is bad.  But outputting the request xml I get:

`<?xml version="1.0"?><exacttarget><authorization><username>MyUser</username><password>MyPass</password>
</authorization><system><system_name>email</system_name><action>add</action>
<sub_action>HTMLPaste</sub_action><category/><email_name>Title</email_name>
<email_subject>Subject</email_subject><email_body><![CDATA[<html><body>&nbsp;</body></html>]]></email_body>
</system></exacttarget>`

**Comment by david-mccullars** [comment]
I would suggest trying the above request xml in a direct call to ET (without the gem) and see if you get the same error message.  If so, we need to figure out if the above request xml is someone invalid with regard to the api or if this is indeed a bug on ET's end.

**Comment by broseborough** [comment]
Looks like you guys fixed it by adding the extra escape in /lib/exact-target.rb

Thanks guys
